# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
        migrations.RunSQL(
            'ALTER TABLE "post_post_category" RENAME TO "post_post_categories";',
            reverse_sql='ALTER TABLE "post_post_categories" RENAME TO "post_post_category";'
        ),
    ]
