# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170225_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('nobody', 'Hidden for all'), ('admin', 'Visible only for admin'), ('user', 'Visible only for resisted user'), ('all', 'Visible for all')], default='nobody', max_length=6),
        ),
    ]
