# Generated by Django 6.0 on 2026-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0012_auto_20170302_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                db_table="post_post_category",
                related_name="category",
                to="post.category",
            ),
        ),
    ]
